=== SoniaALLSauces/Proyecto1920_LMGSI_SAL/1920_LMGSI_SAL/ud4/schema15.xsd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- Autor: Sonia Anton Llanes -->
<!-- Fecha: 13 de febrero de 2020 -->

<!-- Enunciado ejercicio -->
<!-- Esquema xml15: Uso de todos los elementos de libre eleccion -->

<!-- Elementos Simples: -->

<!-- Elementos Complejos: -->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" > 
    <xs:element name="floristeria">
	<xs:complexType>
            <xs:sequence>
		<xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
			<xs:sequence>
                            <xs:element name="fecha" type="xs:date"/>
                            <xs:element name="numeropedido" type="xs:integer"/>
                            <xs:element name="cliente">
                                <xs:complexType>
                                    <xs:simpleContent>
					<xs:extension base="xs:string">
                                            <xs:attribute name="nombre" type="xs:string"/>
					</xs:extension>
                                    </xs:simpleContent>
				</xs:complexType>
                            </xs:element>
                            <xs:element name="envio_benavente" type="xs:boolean" default="true"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="codigopostal" type="xs:string"/>
                            <xs:element name="telefono" type="xs:string"/>
                            <xs:element name="regalo" type="xs:string" fixed="margaritas"/>
                        </xs:sequence>
                    </xs:complexType>
		</xs:element>
            </xs:sequence>
	</xs:complexType>
    </xs:element>
</xs:schema>

=== SoniaALLSauces/Proyecto1920_LMGSI_SAL/1920_LMGSI_SAL/ud4/xml15.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- Autor: Sonia Anton Llanes -->
<!-- Fecha: 13 de febrero de 2020 -->

<!-- Enunciado ejercicio -->
<!-- Uso de todos los elementos de libre eleccion -->


<floristeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema15.xsd">
	<pedido>
		<fecha>2020-02-13</fecha>
		<numeropedido>01</numeropedido>
		<cliente nombre="Faustino Gomez">71200423</cliente>
		<envio_benavente/>
		<direccion>c/ Maragatos, 4</direccion>
		<codigopostal/>
		<telefono>654321987</telefono>
		<regalo/>
	</pedido>
	<pedido>
		<fecha>2020-02-18</fecha>
		<numeropedido>02</numeropedido>
		<cliente nombre="Margarita Perez">11452865</cliente>
		<envio_benavente/>false</envio_benavente/>
		<direccion>avd/ Los Fresnos, 14</direccion>
		<codigopostal>49100</codigopostal>
		<telefono>698745213</telefono>
		<regalo/>
	</pedido>
</floristeria>
